irc.freenode.net: 
  :nick: "NinjaBot"
  :channels: 
     - "#dev-co"
     - "#shapado"
  :port: 6667
  :realname: "Bot"
  :verbose: true
  :version: "NinjaBot v0.0.1"
  :identify:
    :password: "secret"
